<?php
// Script de prueba para verificar el listado corregido
echo "<!DOCTYPE html>";
echo "<html lang='es'>";
echo "<head>";
echo "<meta charset='UTF-8'>";
echo "<meta name='viewport' content='width=device-width, initial-scale=1.0'>";
echo "<title>Test Listado Corregido</title>";
echo "<style>";
echo "body { margin: 0; padding: 0; font-family: Arial, sans-serif; height: 100vh; overflow: hidden; }";
echo ".test-container {";
echo "    width: 100vw;";
echo "    height: 100vh;";
echo "    background: linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%);";
echo "    display: flex;";
echo "    flex-direction: column;";
echo "    padding: 20px;";
echo "    box-sizing: border-box;";
echo "}";
echo ".test-header {";
echo "    background: rgba(255, 255, 255, 0.9);";
echo "    padding: 15px 20px;";
echo "    border-radius: 12px;";
echo "    margin-bottom: 20px;";
echo "    box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1);";
echo "    flex-shrink: 0;";
echo "}";
echo ".test-content {";
echo "    flex: 1;";
echo "    background: rgba(255, 255, 255, 0.9);";
echo "    border-radius: 12px;";
echo "    padding: 20px;";
echo "    box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1);";
echo "    overflow: auto;";
echo "    display: flex;";
echo "    flex-direction: column;";
echo "}";
echo ".test-table-container {";
echo "    flex: 1;";
echo "    background: white;";
echo "    border: 1px solid #ddd;";
echo "    border-radius: 8px;";
echo "    overflow: hidden;";
echo "    display: flex;";
echo "    flex-direction: column;";
echo "}";
echo ".test-table-header {";
echo "    background: rgba(74, 222, 128, 0.1);";
echo "    padding: 10px 15px;";
echo "    border-bottom: 1px solid #ddd;";
echo "    flex-shrink: 0;";
echo "}";
echo ".test-table-content {";
echo "    flex: 1;";
echo "    overflow: auto;";
echo "    padding: 10px;";
echo "}";
echo ".test-table {";
echo "    width: 100%;";
echo "    border-collapse: collapse;";
echo "    font-size: 12px;";
echo "    table-layout: fixed;";
echo "}";
echo ".test-table th {";
echo "    background: #007bff;";
echo "    color: white;";
echo "    padding: 10px 6px;";
echo "    text-align: left;";
echo "    font-weight: 600;";
echo "    white-space: nowrap;";
echo "    position: sticky;";
echo "    top: 0;";
echo "    z-index: 10;";
echo "    overflow: hidden;";
echo "    text-overflow: ellipsis;";
echo "}";
echo ".test-table td {";
echo "    padding: 8px 6px;";
echo "    border: 1px solid #ddd;";
echo "    vertical-align: top;";
echo "    overflow: hidden;";
echo "    text-overflow: ellipsis;";
echo "    white-space: nowrap;";
echo "}";
echo ".test-table tr:nth-child(even) { background: #f8f9fa; }";
echo ".test-table tr:hover { background: #e3f2fd; }";
echo "/* Ajustar anchos de columnas específicas */";
echo ".test-table th:nth-child(1), .test-table td:nth-child(1) { width: 6%; }";
echo ".test-table th:nth-child(2), .test-table td:nth-child(2) { width: 6%; }";
echo ".test-table th:nth-child(3), .test-table td:nth-child(3) { width: 8%; }";
echo ".test-table th:nth-child(4), .test-table td:nth-child(4) { width: 10%; }";
echo ".test-table th:nth-child(5), .test-table td:nth-child(5) { width: 15%; }";
echo ".test-table th:nth-child(6), .test-table td:nth-child(6) { width: 15%; }";
echo ".test-table th:nth-child(7), .test-table td:nth-child(7) { width: 8%; }";
echo ".test-table th:nth-child(8), .test-table td:nth-child(8) { width: 8%; }";
echo ".test-table th:nth-child(9), .test-table td:nth-child(9) { width: 8%; }";
echo ".test-table th:nth-child(10), .test-table td:nth-child(10) { width: 8%; }";
echo ".test-table th:nth-child(11), .test-table td:nth-child(11) { width: 8%; }";
echo ".status-info {";
echo "    background: #e7f3ff;";
echo "    border: 1px solid #b3d9ff;";
echo "    padding: 15px;";
echo "    border-radius: 8px;";
echo "    margin-bottom: 20px;";
echo "}";
echo "</style>";
echo "</head>";
echo "<body>";

echo "<div class='test-container'>";
echo "<div class='test-header'>";
echo "<h1>🧪 Test Listado Corregido</h1>";
echo "<p>Verificando que el listado se muestre correctamente sin scroll horizontal</p>";
echo "</div>";

echo "<div class='test-content'>";
echo "<div class='status-info'>";
echo "<h3>✅ Correcciones Implementadas</h3>";
echo "<ul>";
echo "<li><strong>Tabla con table-layout: fixed</strong> - Distribución automática de columnas</li>";
echo "<li><strong>Anchos de columnas optimizados</strong> - Porcentajes específicos para cada columna</li>";
echo "<li><strong>Text-overflow: ellipsis</strong> - Texto largo se corta con ...</li>";
echo "<li><strong>Sin scroll horizontal</strong> - Tabla se ajusta al ancho disponible</li>";
echo "<li><strong>Sección agrandada</strong> - Más espacio para el listado</li>";
echo "</ul>";
echo "</div>";

echo "<div class='test-table-container'>";
echo "<div class='test-table-header'>";
echo "<h3>📋 Listado de Facturas (Simulado)</h3>";
echo "</div>";
echo "<div class='test-table-content'>";
echo "<table class='test-table'>";
echo "<thead>";
echo "<tr>";
echo "<th>ESTAB</th>";
echo "<th>PTO EMI</th>";
echo "<th>SECUENCIAL</th>";
echo "<th>FECHA CREACIÓN</th>";
echo "<th>CLIENTE</th>";
echo "<th>DIRECCIÓN</th>";
echo "<th>TOTAL</th>";
echo "<th>ESTATUS</th>";
echo "<th>RETENCIÓN</th>";
echo "<th>VALOR PAGADO</th>";
echo "<th>OBSERVACIÓN</th>";
echo "</tr>";
echo "</thead>";
echo "<tbody>";

// Generar datos de prueba
for ($i = 1; $i <= 15; $i++) {
    echo "<tr>";
    echo "<td>001</td>";
    echo "<td>001</td>";
    echo "<td>0000000" . $i . "</td>";
    echo "<td>2024-01-" . str_pad($i, 2, '0', STR_PAD_LEFT) . "</td>";
    echo "<td>Cliente Prueba " . $i . " con nombre muy largo para probar el text-overflow</td>";
    echo "<td>Dirección de Prueba " . $i . " con dirección muy larga para probar el text-overflow</td>";
    echo "<td>$" . number_format(rand(100, 1000), 2) . "</td>";
    echo "<td>REGISTRADA</td>";
    echo "<td>$" . number_format(rand(0, 50), 2) . "</td>";
    echo "<td>$" . number_format(rand(100, 1000), 2) . "</td>";
    echo "<td>Observación de prueba " . $i . " con texto muy largo para probar el text-overflow</td>";
    echo "</tr>";
}

echo "</tbody>";
echo "</table>";
echo "</div>";
echo "</div>";

echo "<div style='margin-top: 20px; padding: 15px; background: #f8f9fa; border-radius: 8px;'>";
echo "<h3>🎯 Verificaciones</h3>";
echo "<ul>";
echo "<li>✅ <strong>Sin scroll horizontal:</strong> La tabla se ajusta al ancho disponible</li>";
echo "<li>✅ <strong>Texto largo:</strong> Se corta con ... cuando es muy largo</li>";
echo "<li>✅ <strong>Columnas equilibradas:</strong> Distribución automática del espacio</li>";
echo "<li>✅ <strong>Sección agrandada:</strong> Más espacio para el contenido</li>";
echo "<li>✅ <strong>Responsive:</strong> Se adapta a diferentes tamaños de pantalla</li>";
echo "</ul>";
echo "</div>";

echo "</div>";
echo "</div>";

echo "<script>";
echo "// Detectar si hay scroll horizontal";
echo "function checkHorizontalScroll() {";
echo "    const tableContent = document.querySelector('.test-table-content');";
echo "    const hasHorizontalScroll = tableContent.scrollWidth > tableContent.clientWidth;";
echo "    ";
echo "    if (hasHorizontalScroll) {";
echo "        console.log('❌ Hay scroll horizontal');";
echo "        document.title = 'Test Listado - ❌ Scroll Horizontal Detectado';";
echo "    } else {";
echo "        console.log('✅ Sin scroll horizontal');";
echo "        document.title = 'Test Listado - ✅ Sin Scroll Horizontal';";
echo "    }";
echo "}";
echo "";
echo "// Verificar al cargar y al cambiar el tamaño";
echo "window.addEventListener('load', checkHorizontalScroll);";
echo "window.addEventListener('resize', checkHorizontalScroll);";
echo "</script>";

echo "</body>";
echo "</html>";
?> 